services: 
  ollama:
    volumes:
      - ${BASE_PATH}/ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: docker.io/ollama/ollama:latest
    ports:
      - 7869:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ${BASE_PATH}/ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${UI_PORT}:8080
    environment:
      - OLLAMA_BASE_URLS=http://ollama:11434
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=Homelab AI
      - WEBUI_URL=${HOST_URL}:${UI_PORT}
      - WEBUI_SECRET_KEY=${KEY}
      - NO_PROXY=host.docker.internal
    restart: unless-stopped
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false
