services: 
  ollama:
    volumes:
      - ${BASE_PATH}/ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: docker.io/ollama/ollama:latest
    ports:
      - 7869:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLAMA_MAX_LOADED_MODELs=1
      - OLAMA_NUM_PARALLEL=1
    networks:
      - ollama-docker
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ${BASE_PATH}/ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${UI_PORT}:8080
    environment:
      - OLLAMA_BASE_URLS=http://ollama:11434
      - ENV=dev
      - WEBUI_AUTH=${AUTH}
      - WEBUI_NAME=Homelab AI
      - WEBUI_URL=${HOST_URL}:${UI_PORT}
      - WEBUI_SECRET_KEY=${KEY}
      - NO_PROXY=host.docker.internal
    restart: unless-stopped
    networks:
      - ollama-docker

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - ${SEARCH_PORT}:8080
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - BASE_URL=http://${HOST_URL}:${SEARCH_PORT}/
networks:
  ollama-docker:
    external: false
